USE [master]
GO
/****** Object:  Database [PRUEBA]    Script Date: 17/07/2025 22:24:56 ******/
CREATE DATABASE [PRUEBA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRUEBA', FILENAME = N'D:\SQLDATA\PRUEBA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRUEBA_log', FILENAME = N'D:\SQLLOG\PRUEBA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PRUEBA] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRUEBA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PRUEBA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PRUEBA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PRUEBA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PRUEBA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PRUEBA] SET ARITHABORT OFF 
GO
ALTER DATABASE [PRUEBA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PRUEBA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PRUEBA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PRUEBA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PRUEBA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PRUEBA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PRUEBA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PRUEBA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PRUEBA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PRUEBA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PRUEBA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PRUEBA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PRUEBA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PRUEBA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PRUEBA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PRUEBA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PRUEBA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PRUEBA] SET RECOVERY FULL 
GO
ALTER DATABASE [PRUEBA] SET  MULTI_USER 
GO
ALTER DATABASE [PRUEBA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PRUEBA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PRUEBA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PRUEBA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PRUEBA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PRUEBA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PRUEBA', N'ON'
GO
ALTER DATABASE [PRUEBA] SET QUERY_STORE = OFF
GO
USE [PRUEBA]
GO
/****** Object:  Table [dbo].[ATENCION_CLIENTE]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATENCION_CLIENTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CLIENTE_ID] [int] NOT NULL,
	[MOTIVO_ID] [int] NOT NULL,
	[FECHA_ALTA] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](100) NOT NULL,
	[APELLIDOS] [varchar](100) NOT NULL,
	[CELULAR] [varchar](20) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[SEXO] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CELULAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MOTIVO]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MOTIVO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[DESCRIPCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ATENCION_CLIENTE] ADD  DEFAULT (getdate()) FOR [FECHA_ALTA]
GO
ALTER TABLE [dbo].[ATENCION_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_Atencion_Cliente] FOREIGN KEY([CLIENTE_ID])
REFERENCES [dbo].[CLIENTE] ([ID])
GO
ALTER TABLE [dbo].[ATENCION_CLIENTE] CHECK CONSTRAINT [FK_Atencion_Cliente]
GO
ALTER TABLE [dbo].[ATENCION_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_Atencion_Motivo] FOREIGN KEY([MOTIVO_ID])
REFERENCES [dbo].[MOTIVO] ([ID])
GO
ALTER TABLE [dbo].[ATENCION_CLIENTE] CHECK CONSTRAINT [FK_Atencion_Motivo]
GO
/****** Object:  StoredProcedure [dbo].[sp_InsertarAtencion]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_InsertarAtencion]
    @ClienteId INT,
    @MotivoId INT
AS
BEGIN
    INSERT INTO ATENCION_CLIENTE (Cliente_Id, Motivo_Id, Fecha_Alta)
    VALUES (@ClienteId, @MotivoId, GETDATE());
END
GO
/****** Object:  StoredProcedure [dbo].[sp_InsertarCliente]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_InsertarCliente]
    @Nombre VARCHAR(100),
    @Apellidos VARCHAR(100),
    @Celular VARCHAR(20),
    @Email VARCHAR(100),
    @Sexo VARCHAR(10)
AS
BEGIN
    INSERT INTO CLIENTE (Nombre, Apellidos, Celular, Email, Sexo)
    VALUES (@Nombre, @Apellidos, @Celular, @Email, @Sexo);
END
GO
/****** Object:  StoredProcedure [dbo].[sp_InsertarMotivo]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_InsertarMotivo]
    @Descripcion VARCHAR(50)
AS
BEGIN
    INSERT INTO MOTIVO (Descripcion)
    VALUES (@Descripcion);
END
GO
/****** Object:  StoredProcedure [dbo].[sp_ListarAtencionesPorFechas]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_ListarAtencionesPorFechas]
    @Desde DATE,
    @Hasta DATE
AS
BEGIN
    SELECT 
        C.Nombre,
        C.Apellidos,
        M.DESCRIPCION AS Motivo,
        A.Fecha_Alta
    FROM ATENCION_CLIENTE A
    INNER JOIN CLIENTE C ON A.CLIENTE_ID = C.Id
    INNER JOIN MOTIVO M ON A.MOTIVO_ID = M.Id
    WHERE cast(A.Fecha_Alta as date) BETWEEN @Desde AND @Hasta
    ORDER BY A.FECHA_ALTA DESC;
END
GO
/****** Object:  StoredProcedure [dbo].[sp_ListarClientes]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_ListarClientes]
AS
BEGIN
    SELECT Id, Nombre, Apellidos, Celular, Email, Sexo
    FROM CLIENTE
    ORDER BY Nombre
END
GO
/****** Object:  StoredProcedure [dbo].[sp_ListarMotivos]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_ListarMotivos]
AS
BEGIN
    SELECT Id, Descripcion
    FROM MOTIVO
    ORDER BY Id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_VerificarAtencionHoy]    Script Date: 17/07/2025 22:24:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_VerificarAtencionHoy]
    @Celular VARCHAR(20)
AS
BEGIN
    SELECT ac.Id, c.Nombre, c.Apellidos, m.Descripcion AS Motivo, ac.Fecha_Alta
    FROM ATENCION_CLIENTE ac
    INNER JOIN CLIENTE c ON c.Id = ac.Cliente_Id
    INNER JOIN MOTIVO m ON m.Id = ac.Motivo_Id
    WHERE c.Celular = @Celular
      AND CAST(ac.Fecha_Alta AS DATE) = CAST(GETDATE() AS DATE)
END
GO
USE [master]
GO
ALTER DATABASE [PRUEBA] SET  READ_WRITE 
GO
